# Source: jxboot-helmfile-resources/templates/jx-gcjobs-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gcjobs
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - jenkins.io
    resources:
      - environments
      - plugins
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - jobs
    verbs:
      - get
      - delete
      - list
